SELECT
    AUTHOR_ID,
    AUTHOR_NAME,
    CATEGORY,
    SUM(TOTAL) AS TOTAL_SALES
FROM (
    SELECT
        A.AUTHOR_ID,
        A.AUTHOR_NAME,
        B.CATEGORY,
        B.PRICE * SUM(S.SALES) AS TOTAL
    FROM BOOK B
    JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
    JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
    WHERE S.SALES_DATE >= '2022-01-01' AND S.SALES_DATE < '2022-02-01'
    GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.PRICE
) A
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC