-- 대여 불가 자동차
WITH RENTING_CAR AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE !(START_DATE > '2022-11-30' OR END_DATE < '2022-11-01')
)

SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    TRUNCATE(C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100, 0) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR C
JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE
WHERE
    C.CAR_TYPE IN ('세단', 'SUV')
    AND C.CAR_ID NOT IN (SELECT CAR_ID FROM RENTING_CAR)
    AND D.DURATION_TYPE = '30일 이상'
    AND C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100 >= 500000
    AND C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100 < 2000000