SELECT RI1.FOOD_TYPE, RI1.REST_ID, RI1.REST_NAME, RI1.FAVORITES
FROM REST_INFO RI1
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) RI2
ON RI1.FOOD_TYPE = RI2.FOOD_TYPE AND RI1.FAVORITES = RI2.MAX_FAVORITES
ORDER BY RI1.FOOD_TYPE DESC;
