SELECT
    ID,
    CASE
        WHEN P <= 25 THEN 'CRITICAL'
        WHEN P <= 50 THEN 'HIGH'
        WHEN P <= 75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT
        ID,
        (PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC)) * 100 AS P
    FROM
        ECOLI_DATA
) AS SUB
ORDER BY
    ID