SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    GENDER,
    COUNT(DISTINCT OS.USER_ID) AS USERS
FROM
    ONLINE_SALE OS
JOIN
    USER_INFO UI ON OS.USER_ID = UI.USER_ID
WHERE
    UI.GENDER IS NOT NULL
GROUP BY
    YEAR(SALES_DATE),
    MONTH(SALES_DATE),
    GENDER
ORDER BY
    YEAR(SALES_DATE),
    MONTH(SALES_DATE),
    GENDER;