-- 2021년에 가입한 전체 회원
WITH JOINS AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED >= '2021-01-01' AND JOINED < '2022-01-01'
)

SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM JOINS), 1) AS PUCHASED_RATIO
FROM
    ONLINE_SALE
WHERE
    USER_ID IN (SELECT * FROM JOINS)
GROUP BY
    YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY
    YEAR, MONTH