SELECT
    YEAR(S.SALES_DATE) AS YEAR,
    MONTH(S.SALES_DATE) AS MONTH,
    COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT U.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED >= '2021-01-01' AND JOINED < '2022-01-01'), 1
    ) AS PUCHASED_RATIO
FROM
    ONLINE_SALE S
JOIN
    USER_INFO U ON S.USER_ID = U.USER_ID
    AND U.JOINED >= '2021-01-01' AND U.JOINED < '2022-01-01'
GROUP BY
    YEAR, MONTH
ORDER BY
    YEAR, MONTH