SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.PRICE * SUM(O.AMOUNT) AS TOTAL_SALES
FROM
    FOOD_PRODUCT P
JOIN
    FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE
    O.PRODUCE_DATE >= '2022-05-01' AND O.PRODUCE_DATE < '2022-06-01'
GROUP BY
    P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY
    TOTAL_SALES DESC, PRODUCT_ID