WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM HOURS WHERE HOUR < 23
)

SELECT
    H.HOUR,
    IFNULL(A.COUNT, 0) AS COUNT
FROM
    HOURS H
LEFT JOIN (
    SELECT
        HOUR(DATETIME) AS HOUR,
        COUNT(*) AS COUNT
    FROM
        ANIMAL_OUTS
    GROUP BY
        HOUR
) A ON H.HOUR = A.HOUR
ORDER BY
    H.HOUR