SELECT
    U.USER_ID,
    U.NICKNAME,
    W.TOTAL_SALES
FROM USED_GOODS_USER U
JOIN (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING TOTAL_SALES >= 700000
) W ON U.USER_ID = W.WRITER_ID
ORDER BY
    W.TOTAL_SALES