WITH AVGS AS (
    SELECT EMP_NO, AVG(SCORE) AS SCORE_AVG
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT
    E.EMP_NO,
    E.EMP_NAME,
    CASE
        WHEN SCORE_AVG >= 96 THEN 'S'
        WHEN SCORE_AVG >= 90 THEN 'A'
        WHEN SCORE_AVG >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN SCORE_AVG >= 96 THEN E.SAL * 0.2
        WHEN SCORE_AVG >= 90 THEN E.SAL * 0.15
        WHEN SCORE_AVG >= 80 THEN E.SAL * 0.1
        ELSE 0
    END AS BONUS
FROM
    HR_EMPLOYEES E
JOIN
    AVGS A ON E.EMP_NO = A.EMP_NO
ORDER BY
    E.EMP_NO