SELECT
    M.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM
    REST_REVIEW R
JOIN
    MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID
WHERE
    M.MEMBER_ID IN (
        SELECT MEMBER_ID
        FROM (
            SELECT MEMBER_ID, RANK() OVER (ORDER BY COUNT(*) DESC) AS RK
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        ) A
        WHERE RK = 1
    )
ORDER BY
    REVIEW_DATE, REVIEW_TEXT