SELECT
    CATEGORY,
    PRICE AS MAX_PRICE,
    PRODUCT_NAME
FROM (
    SELECT
        PRODUCT_NAME,
        CATEGORY,
        PRICE,
        RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RK
    FROM
        FOOD_PRODUCT
    WHERE
        CATEGORY IN ('과자', '국', '김치', '식용유')
) AS A
WHERE
    RK = 1
ORDER BY
    MAX_PRICE DESC