WITH FE AS (
    SELECT SUM(CODE) AS FE_CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),
DEV_GRADE AS (
    SELECT
        CASE
            WHEN (SKILL_CODE & (SELECT FE_CODE FROM FE))
                AND (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python'))
                THEN 'A'
            WHEN (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#'))
                THEN 'B'
            WHEN (SKILL_CODE & (SELECT FE_CODE FROM FE))
                THEN 'C'
        END AS GRADE,
        ID,
        EMAIL
    FROM
        DEVELOPERS
)

SELECT GRADE, ID, EMAIL
FROM DEV_GRADE
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID